### ISSUE TITLE
SmartAI - SMART_EVENT_JUST_SUMMONED and SMART_EVENT_DAMAGED_TARGET are never triggered

### ISSUE THREAD

**Issue by kelno** [SunstriderProject/Sunstrider-Issues#59]

**Comment by kelno** [comment]
Fixed in Nqsty/Sunstrider@57075e5ab1b1a25e69b56361ee2c16308a70b0eb

**Comment by kelno** [comment]
Testing needed here : Just check if both events are called (with any actions, that doesn't change anything).

**Comment by Nqsty** [comment]
Gameobject : 182164
SMART_EVENT_JUST_SUMMONED not working

**Comment by kelno** [comment]
SmartAI probably dont work with gameobjects yet.
We still need to test the two events on a creature.

**Comment by Nqsty** [comment]
* SMART_EVENT_JUST_SUMMONED : tested with [Hand of Kargath (22374)](http://www.wowhead.com/npc=22374), still not working atm meaning, it doesnt aggro the player on spawn.

**Comment by kelno** [comment]
Wasn't working when summoned by player, fixed in :
kelno/sunstrider@da6d025230a060a0ab63e3356e9b4f437b6ac4a7 

Your event still has another problem, the adds aren't properly attacking the player either (or didn't when I tested). Maybe you can add a call for help action on the hand of Kargath.

**Comment by kelno** [comment]
SMART_EVENT_DAMAGED_TARGET still need testing.

**Comment by kelno** [comment]
Suggested test :
Have a creature cast a spell at you, then have an event SMART_EVENT_DAMAGED_TARGET making the creature suicide (ACTION_DIE TARGET_SELF) when making damage.
